# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'JKNetworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'AFNetworking', '3.2.1'
  # Pods for JKNetworking

end
